version: '3.1'
services:
  postgres:
    image: postgres:12
    user: 1000:1000
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - docker.env

  adminer:
    image: adminer
    ports:
      - 8090:8080
